sudo: false
language: python
cache:
  directories:
    - $XDG_CACHE_HOME/pip
before_cache:
  - rm -f $XDG_CACHE_HOME/pip/log/debug.log
python:
  - "3.5"
env:
  global:
    - XDG_CACHE_HOME=$HOME/.cache
  matrix:
    - TOX_ENV=flake8
    - TOX_ENV=docs
    - TOX_ENV=py34-django1.8-drf3.3-jwt1.7
    - TOX_ENV=py34-django1.8-drf3.3-jwt1.8
    - TOX_ENV=py34-django1.8-drf3.4-jwt1.7
    - TOX_ENV=py34-django1.8-drf3.4-jwt1.8
    - TOX_ENV=py34-django1.9-drf3.3-jwt1.7
    - TOX_ENV=py34-django1.9-drf3.3-jwt1.8
    - TOX_ENV=py34-django1.9-drf3.4-jwt1.7
    - TOX_ENV=py34-django1.9-drf3.4-jwt1.8
    - TOX_ENV=py34-django1.10-drf3.3-jwt1.7
    - TOX_ENV=py34-django1.10-drf3.3-jwt1.8
    - TOX_ENV=py34-django1.10-drf3.4-jwt1.7
    - TOX_ENV=py34-django1.10-drf3.4-jwt1.8
    - TOX_ENV=py35-django1.8-drf3.3-jwt1.7
    - TOX_ENV=py35-django1.8-drf3.3-jwt1.8
    - TOX_ENV=py35-django1.8-drf3.4-jwt1.7
    - TOX_ENV=py35-django1.8-drf3.4-jwt1.8
    - TOX_ENV=py35-django1.9-drf3.3-jwt1.7
    - TOX_ENV=py35-django1.9-drf3.3-jwt1.8
    - TOX_ENV=py35-django1.9-drf3.4-jwt1.7
    - TOX_ENV=py35-django1.9-drf3.4-jwt1.8
    - TOX_ENV=py35-django1.10-drf3.3-jwt1.7
    - TOX_ENV=py35-django1.10-drf3.3-jwt1.8
    - TOX_ENV=py35-django1.10-drf3.4-jwt1.7
    - TOX_ENV=py35-django1.10-drf3.4-jwt1.8
install:
  - travis_retry pip install tox codecov
script:
  - tox -e $TOX_ENV
after_success:
  - codecov -e $TOX_ENV
notifications:
  email: false
